apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-iterate
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/min-scale: "1"  
spec:
  params:
  # - name: annotations
  #   value:
  #     autoscaling.knative.dev/minScale: "2"

    - name: gitops_repository_owner
      value: vikparmar
    - name: gitops_repository_name
      value: tap-gitops
  source:
    git:
      url: https://github.com/vikparmar/tanzu-java-web-app-2023.git
      ref:
        branch: main
